### PR TITLE
Workaround to pass `/bigobj` to users of the library

### PR DESCRIPTION
**Pull request by Klaim**
Discussion https://github.com/build2/build2/issues/316

Based on https://github.com/lyrahgames/build2-libigl/pull/1 so ignore the symlink changes here.

### CODE REVIEW

**Comment by lyrahgames** [comment]
I have already tried this workaround myself before. It is indeed working for the update and the standard testing stage. But as soon as the installed version needs to be tested the flag `/bigobj` vanished from compilation. It is part of the pkg-config file but maybe it is not parsed correctly. So, for now requiring the user to add this option is probably a better workaround. What do you think?

**Comment by Klaim** [comment]
> So, for now requiring the user to add this option is probably a better workaround. What do you think?

Yeah that works, it's just unfortunate and many people will forget about it 😬 

As for the install version, let me try locally.

**Comment by Klaim** [comment]
OK I managed to confirm that although the installed `libigl-core.pc` does contain `/bigobj`:
```
Cflags: -IE:\\tests\\build2-libigl\\install\\include -DNOMINMAX /bigobj
```
when making an exe project using that installed version, we dont get the `/bigobj` flag in the build. Not sure what's happening here...

**Comment by lyrahgames** [comment]
Thank you for figuring that out.

**Pull request closed without merging**
